import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { Project } from '../types';

export async function exportProjectAsZip(project: Project): Promise<void> {
  const zip = new JSZip();
  
  // Add all files to zip
  for (const file of project.files) {
    zip.file(file.path, file.content);
  }
  
  // Generate README
  const readme = generateReadme(project);
  zip.file('README.md', readme);
  
  // Generate zip
  const blob = await zip.generateAsync({ type: 'blob' });
  
  // Download
  saveAs(blob, `${project.name}.zip`);
}

function generateReadme(project: Project): string {
  return `# ${project.name}

Generated by STLoop Web

## Description
${project.description}

## Board
${project.board}

## Build Instructions

1. Install Zephyr SDK and west tool
2. Navigate to project directory
3. Build:
   west build -b ${project.board}

4. Flash:
   west flash

## Files
${project.files.map(f => `- ${f.path}`).join('\n')}

## Generated At
${new Date(project.createdAt).toLocaleString()}
`;
}
