import { Project, ProjectFile } from '../types';

const ZEPHYR_SYSTEM_PROMPT = `You are a Zephyr RTOS expert. Generate C code following these rules:

1. Headers (required):
   #include <zephyr/kernel.h>
   #include <zephyr/drivers/gpio.h>

2. Hardware access (use Device Tree):
   #define LED0_NODE DT_ALIAS(led0)
   static const struct gpio_dt_spec led = GPIO_DT_SPEC_GET(LED0_NODE, gpios);

3. GPIO operations:
   - Check: gpio_is_ready_dt(&led)
   - Configure: gpio_pin_configure_dt(&led, GPIO_OUTPUT_ACTIVE)
   - Control: gpio_pin_toggle_dt(&led)

4. Timing: k_msleep(1000)

5. Output ONLY valid C code, no markdown or explanations`;

const BASE_CMAKELISTS = `cmake_minimum_required(VERSION 3.20.0)
find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
project(stloop_app)

target_sources(app PRIVATE src/main.c)
`;

const BASE_PRJ_CONF = `# Zephyr Project Configuration
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_GPIO=y
CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=100000000
CONFIG_MAIN_STACK_SIZE=1024
`;

export async function generateZephyrProject(
  prompt: string,
  board: string,
  apiKey?: string
): Promise<Project> {
  // For demo/development, generate a simple blink example
  // In production, this would call the LLM API
  
  const mainC = generateMainC(prompt);
  
  const projectId = Math.random().toString(36).substr(2, 9);
  const projectName = prompt.split(' ').slice(0, 3).join('_') || 'project';
  
  const files: ProjectFile[] = [
    { path: 'CMakeLists.txt', content: BASE_CMAKELISTS },
    { path: 'prj.conf', content: generatePrjConf(prompt) },
    { path: 'src/main.c', content: mainC },
  ];
  
  return {
    id: projectId,
    name: projectName,
    board,
    description: prompt,
    files,
    createdAt: Date.now(),
  };
}

function generateMainC(prompt: string): string {
  const lowerPrompt = prompt.toLowerCase();
  
  // Simple pattern matching for demo
  if (lowerPrompt.includes('blink') || lowerPrompt.includes('闪烁')) {
    return `/*
 * Zephyr Application
 * Generated by STLoop Web
 */

#include <zephyr/kernel.h>
#include <zephyr/drivers/gpio.h>

/* LED0 is the onboard LED (PA5 on Nucleo-F411RE) */
#define LED0_NODE DT_ALIAS(led0)
static const struct gpio_dt_spec led = GPIO_DT_SPEC_GET(LED0_NODE, gpios);

int main(void)
{
    int ret;

    if (!gpio_is_ready_dt(&led)) {
        return -1;
    }

    ret = gpio_pin_configure_dt(&led, GPIO_OUTPUT_ACTIVE);
    if (ret < 0) {
        return -1;
    }

    while (1) {
        ret = gpio_pin_toggle_dt(&led);
        if (ret < 0) {
            return -1;
        }
        k_msleep(1000);
    }

    return 0;
}`;
  }
  
  // Default template
  return `/*
 * Zephyr Application
 * Generated by STLoop Web
 */

#include <zephyr/kernel.h>
#include <zephyr/drivers/gpio.h>

int main(void)
{
    printk("Hello from STLoop!\\n");
    
    while (1) {
        k_msleep(1000);
    }
    
    return 0;
}`;
}

function generatePrjConf(prompt: string): string {
  let conf = BASE_PRJ_CONF;
  
  const lowerPrompt = prompt.toLowerCase();
  
  if (lowerPrompt.includes('uart') || lowerPrompt.includes('serial')) {
    conf += 'CONFIG_UART_INTERRUPT_DRIVEN=y\n';
  }
  
  if (lowerPrompt.includes('i2c')) {
    conf += 'CONFIG_I2C=y\n';
  }
  
  if (lowerPrompt.includes('spi')) {
    conf += 'CONFIG_SPI=y\n';
  }
  
  if (lowerPrompt.includes('pwm')) {
    conf += 'CONFIG_PWM=y\n';
  }
  
  if (lowerPrompt.includes('adc')) {
    conf += 'CONFIG_ADC=y\n';
  }
  
  return conf;
}

export async function generateCodeWithLLM(
  prompt: string,
  board: string,
  apiKey: string
): Promise<string> {
  // TODO: Implement actual LLM API call
  // This would call OpenAI/Kimi API
  throw new Error('LLM API not implemented yet. Please use demo mode.');
}
